### ISSUE TITLE
Applications Menu doesn't open grid view correctly

### ISSUE THREAD

**Issue by ryonakano** [elementary/applications-menu#112]
![screenshot from 2018-07-07 22-28-57](https://user-images.githubusercontent.com/26003928/42411402-68eea934-8236-11e8-8ecf-26a6fcd85100.png)

Applications Menu displays wrong row & column number items in the first launch.
In this screenshot above, its row number is 5 but actually it displays as if its row number is 4. This issue happens only the first launch of Applications Menu.

Also at the same time, there is no switcher in the bottom.

On Juno Beta1

**Comment by arshubham** [comment]
Adding one more screenshot for clarity:
![screenshot from 2018-07-06 12-13-55](https://user-images.githubusercontent.com/14235191/42411937-4039ed5a-8222-11e8-9111-d1c5d2e6e613.png)

**Comment by donadigo** [comment]
Reopening because I'm not sure if the branch above really fixed it and GitHub closed the issue because I used "fix #number" in the description.

**Comment by ryonakano** [comment]
It seems that the page switcher at the bottom of Applications Menu is invisible in the first launch.

**Comment by donadigo** [comment]
@ryonakano that's what #118 fixed.

**Comment by WebShapedBiz** [comment]
Same problem here, with 4 columns display configuration while in dconf and gschema.xml is correctly defined 5 columns.
It's not troubling to change this in Tweaks or dconf editor, but for some reason, the issue is returning after each suspend.

**Comment by WebShapedBiz** [comment]
It's a shame that the new release didn't address this issue. It has been more than a year now that we have this problem.

**Comment by jeremypw** [comment]
I could not reproduce this on Juno unstable (Slingshot v2.4.3) - I'll check again after installing v2.4.4

**Comment by WebShapedBiz** [comment]
Thank you Jeremy.
For me, this has been an issue from the day one on Juno and I believe in
Loki as well. In all the places (dconf and config files) the column number
is always correct - 5. But it gets ignored on each reboot and after
slingshot restart/refresh. For example, in both dconf-editor and
elementary-tweaks, the number of columns is 5 but I always need to flip it
back and forth to force it on slingshot.

Best regards,

Sinisa Perovic
Webshaped Business OÜ

Web: https://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

**Comment by jeremypw** [comment]
Strange!  It rather looks like, for you, the category view (four columns) is being used when in grid view mode.  However, I just tried this in Juno stable as well and could not reproduce there either. Maybe some hardware dependent race condition?  If you switch between grid and category mode with the faulty view open, what happens?

**Comment by jeremypw** [comment]
If you close in category mode, then this should be remembered and sligshot should then re-open in category mode - does this happen?  Does it make any difference what mode you last closed slingshot in?

**Comment by WebShapedBiz** [comment]
I'm having "Category view" as my default view and it always gets opened
with 4 columns view. When I switch to "Icon view" I always get nice 5
column view. However, when I go back to category view, I'm having 4 columns
again :-( That is until flipping the setup in dconf-editor. I can show you
with screencast if you want.
This is happening on all 3 of my computers running Elementary OS Juno with
completely different configurations.

Best regards,

Sinisa Perovic
Webshaped Business OÜ

Web: https://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

**Comment by jeremypw** [comment]
I thought this was the intended behaviour - the category sidebar replaces one of the columns in grid view so the window does not resize.  The screenshots shown above are both showing four columns in grid view (which is incorrect) but for me, I always get 5 columns in grid view.

**Comment by jeremypw** [comment]
I can confirm that if you flip the column settings then category view shows 5 columns!  I'll have to check the code to see what was intended.

**Comment by WebShapedBiz** [comment]
Cheers @jeremypw.

**Comment by jeremypw** [comment]
This seems to be a separate issue as it applies to category view, not grid view.  I think a new issue should be opened.

**Comment by ryonakano** [comment]
I no longer see this issue on Odin Beta, so closing the issue. Feel free to reopen if someone is still facing this issue.
