### ISSUE TITLE
unit conversion in calculator plugin

### ISSUE THREAD

**Issue by joseph-long** [elementary/applications-menu#114]
In science and engineering, we frequently need to use physical units (and equally frequently, we forget the conversion factors). It would be great if there were a way to quickly get unit-ful quantities out of a calculation (similar to Spotlight and KRunner).

I haven't tracked down the exact place KRunner implements this, but they seem to have a pretty complete set of units and support for manipulating them in calculations. See [the KDE wiki](https://userbase.kde.org/Plasma/Krunner#Calculator) for examples.

The current implementation of the calculator plugin shells out to `bc`, which doesn't appear to have unit support. It seems like KRunner is using [libqalculate](http://qalculate.github.io/) under the hood which has built-in unit support, if introducing a dependency is acceptable.

Alternatively, is it possible for 3rd party apps to install plugins like the calculator one?

**Comment by peteruithoven** [comment]
Maybe `calq` that seems to be the cli of [libqalculate](https://github.com/Qalculate/libqalculate)

```
$ qalc 1+1
1 + 1 = 2
$ qalc 10mm to m
10 * millimeter = 0,01 m
```

For the curious: the current [calculator-plugin](https://github.com/elementary/applications-menu/blob/master/lib/synapse-plugins/calculator-plugin.vala)
