### ISSUE TITLE
[Feature Request] Allow Multiple Strings for Actions such as Shutdown

### ISSUE THREAD

**Issue by amxmln** [elementary/applications-menu#119]
It’s incredibly convenient to be able to shut down the system simply by searching for "shut down" and hitting enter, however in German, I find myself searching for "ausschalten" (turn off) more often than "herunterfahren" (shut down), so would it be possible to add multiple strings to these actions, similarly to how searching for "browser" brings up the installed web-browsers?

This could be beneficial while searching for settings as well, for example "Info" could also show up when searching for "Details".

**Comment by peteruithoven** [comment]
But, the result, should that than have also give a result with the title "Turn Off" or should that display the original (current) title "Shut Down"?

**Comment by peteruithoven** [comment]
I found a way to add additional actions by extending existing ones. This enables also changing the title and description. 

If we want to keep the original title and have it respond to multiple search queries we need to add an extra field to `SystemAction` and go though them, probably here: https://github.com/elementary/applications-menu/blob/master/lib/synapse-plugins/system-managment.vala#L458-L461

**Comment by amxmln** [comment]
I don’t think changing the actual string in the result would is necessary. Searching for “Internet” also brings up all the installed browsers with their correct names after all.

But perhaps it could give users the satisfaction of finding exactly what they were looking for?
