### ISSUE TITLE
Update README.md with latest build instructions

### ISSUE THREAD

**Issue by jameshiew** [elementary/applications-menu#123]
On `master` branch, `make` doesn't work, it looks like `ninja` is used instead.

`libxml2` also needed to be `apt install`ed (on Ubuntu) in order to make a cmake warning about XMLLINT go away.

It would also be nice if there were brief pointers on setting up a productive developer environment (I'm currently modifying a version of the code downloaded with `apt-src install slingshot-launcher`, then doing `apt-src build slingshot-launcher` + `sudo dpkg -i slingshot-launcher{...}.deb` + `killall wingpanel` to effect changes in my DE...)

**Comment by danrabbit** [comment]
Closing because the master branch does indeed use CMake. This project hasn't been ported to Meson yet. See #82
