### ISSUE TITLE
Only react to horizontal touchpad scroll

### ISSUE THREAD

**Issue by cassidyjames** [elementary/applications-menu#124]
Right now paging can be done with both vertical and horizontal touchpad scrolling. However, this creates some undesirable behavior when accidentally swiping a little vertically and horizontally, as the pages seem to switch randomly (swiping from right-to-left, but accidentally a little downward will go to the next and then previous page).

This could be resolved by only listening to horizontal scroll events on touchpads, while still listening for vertical and horizontal scrolls on traditional mice.

**Comment by danrabbit** [comment]
This is fixed now that we're using Hdy.Paginator
