### ISSUE TITLE
Swipe on touch screen to switch pages

### ISSUE THREAD

**Issue by cassidyjames** [elementary/applications-menu#128]
_From @alex285 on January 14, 2018 19:54_

even if i use elementary a lot, every time i open the appLauncher i'm trying to switch to next/previous page by holding down mouse and pushing on right/left

is it possible to add some gestures onWingpanel appLauncher, since it feels a natural way to navigate?

![wingpanel-bug-1](https://user-images.githubusercontent.com/11244308/34920039-0c0d7d2a-f975-11e7-84a0-74c1950fda64.png)

**Comment by cassidyjames** [comment]
Right now you can sideways scroll on a trackpad, or use the mouse wheel on a normal mouse. I'm not sure what you're asking. 

Do you mean switch pages by clicking down, moving the mouse, and then releasing? If so, that's extremely inconsistent with all of GTK and elementary OS and would require weird special casing. It would also likely conflict with the existing drag-and-drop of app icons. It _should_ already work properly on a touch screen (if not, that's a separate bug), but nothing in elementary OS operates that way with a mouse cursor.

**Comment by cassidyjames** [comment]
Also, this repo is for the panel itself. For the app launcher, see [elementary/applications-menu](https://github.com/elementary/applications-menu).

**Comment by cassidyjames** [comment]
_From @alex285 on January 14, 2018 20:48_

@cassidyjames 
> Do you mean switch pages by clicking down, moving the mouse, and then releasing?

yes

> that's extremely inconsistent with all of GTK

i cant remember some GTK app doing that, however that's working on GNOME Shell appOverview (with St). i believe it is a very natural and expected behavior the way elementary application menu is made/designed 

> Also, this repo is for the panel itself.

Sorry about that!

**Comment by cassidyjames** [comment]
I'm going to say no, this doesn't make sense with the rest of the design of GTK and elementary OS. However! It could make sense on a touch display, as right now on touch dragging the page just tries to drag icons out of the menu. So I'll rename this accordingly.

**Comment by zvirdaniel** [comment]
> I'm going to say no, using a mouse in this way doesn't make sense with the rest of the design of GTK and elementary OS. However! It could make sense on a touch display, as right now on touch dragging the page just tries to drag icons out of the menu. So I'll rename this accordingly.

That is also one of the biggest issues when it comes to using elementary witch a touchscreen. How exactly are users supposed to switch pages with a touchscreen, if this does not get impemented before Juno comes out.

**Comment by cassidyjames** [comment]
@zvirdaniel I agree, which is why this issue is marked as confirmed. Since elementary OS does not primarily target touch, it's not the highest priority. However, it is confirmed which means we recognize the issue and plan to resolve it when we have the time. Or someone can come along and offer a fix. :wink:

**Comment by jdmg94** [comment]
It's good to know I'm not the only one thinking about this. I'm trying to implement [GtkGestureSwipe](https://valadoc.org/gtk+-3.0/Gtk.GestureSwipe.html) on the panel's `event_box`. I've properly added the touch mask to the `event_box` and subscribed to the touch signal, however, I'm still unable to determine the swipe direction and there is little to no documentation about it. The linked doc mentions that the velocity and direction are passed but the direction doesn't seem to be there unless the velocity values work as cartesian coordinate which would be weird but not out of the realm of possibility. Any help is appreciated, I'm using vscode so debugging has been an issue as well, I didn't knew vala last week so the tooling is new to me
