### ISSUE TITLE
Flatpak apps doesn't show up

### ISSUE THREAD

**Issue by bilelmoussaoui** [elementary/applications-menu#130]
The Flatpak applications installed on my system doesn't show up.
The desktop files are exported to `/var/lib/flatpak/exports/share/applications/`
The `$XDG_DATA_DIRS` has already the right paths on it 
```
/home/bilelmoussaoui/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share/:/usr/share/gnome:/usr/share/pantheon:/home/bilelmoussaoui/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
```

**Comment by raibtoffoletto** [comment]
Did you follow flatpak's instructions when installing and rebooted your system?
My apps wouldn't show until my next reboot.

**Comment by danrabbit** [comment]
Closing because I can't reproduce this issue any longer. Flatpak apps seem to appear as expected
