### ISSUE TITLE
wingpanel memory consumption after opening app-menu

### ISSUE THREAD

**Issue by Mynock17** [elementary/applications-menu#145]
After booting Juno 5.0 wingpanel uses 16M (measured with smem).
After opening the app-menu 418M ...

**Comment by peteruithoven** [comment]
Isn't this a duplicate of: https://github.com/elementary/applications-menu/issues/117

**Comment by Mynock17** [comment]
Maybe - but this is Juno 5.0 (not beta): Something like this shouldn't happen in a final release.

**Comment by danrabbit** [comment]
Closing as a duplicate of #117
