### ISSUE TITLE
Missing icons on Turkish locale

### ISSUE THREAD

**Issue by payonpowbl** [elementary/applications-menu#154]
![2018-11-02 18-35-26 ekran goruntusu](https://user-images.githubusercontent.com/12845347/47925498-617d5380-decf-11e8-8ad1-903741e6ce85.png)

As you can see here, icons are missing on Juno with Turkish locale selected. That's because the one who translated into Turkish, also translated the "Icon[tr]=X" path too.

I mean as you can see here:
![2018-11-02 18-39-15 ekran goruntusu](https://user-images.githubusercontent.com/12845347/47925823-1f084680-ded0-11e8-92be-a71cdc948d18.png)
`Icon=` string and other `Icon[locale]` strings are `office-calendar` But in `Icon[tr]` it's `ofis-takvim` -which is the direct translation of `office-calendar`- I've fixed the translation and send it to back then the first Juno Beta released but nothing changed.

**Comment by tintou** [comment]
Fixed in each app themselves
