### ISSUE TITLE
Applications menu freezes after every restart

### ISSUE THREAD

**Issue by it-s** [elementary/applications-menu#157]
Description: After every log-in/restart the Applications menu stops working.
1) When "Applications" label is clicked menu does not show up.
2) If repeatedly clicked the wing panel segfaults and restarts.
3) After about 5min menu starts working normally.

elementary OS 5.0 Juno
Dual-Core Intel® Core™ i7-6500U CPU @ 2.50GHz
Intel Corporation HD Graphics 520 (rev 07)
11.7 GB memory

**Comment by peteruithoven** [comment]
Any idea when this started happening? Did this start happening right after you installed Juno? Can you reproduce this from a live image on a usb stick  for example?

The following command gives you a list of the applications you've installed:
```
comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)
```

We for example found an issue with Libreofice icons causing a memory leak:
https://github.com/elementary/applications-menu/issues/117

**Comment by it-s** [comment]
Turns out you were right. The Libreofice .desktop files were left over from my previous install (carried over along with the home directory) once I removed those issue seems to have disappeared.
However I also removed a bunch of other redundant .desktop files, so it could have been any of those.
