### ISSUE TITLE
Prioritize application actions over AppCenter search

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [elementary/applications-menu#158]
I remember that, before the AppCenter debut, I could quickly type the name of the application action, and press Enter, and it would launch that action. Since the release of AppCenter, the "Search for ... in AppCenter" action would be at the top of the list, and as result, actions can't be invoked as fast as before.

![screenshot from 2018-11-18 12 27 12](https://user-images.githubusercontent.com/6058082/48671853-79d7aa00-eb2e-11e8-9f7a-1b9eb5d241ac.png)

My rationale is that application menu is  often used to launch specific actions on the system, and therefore:
- If the specific action exists, the user either expected it there, or didn't know it could already be done with an already-installed app. Either way, the user doesn't want to search the AppCenter.
- If the specific action doesn't exist, AppCenter search is at the top (being the only item on the list), and nothing is changed.

**Comment by Gabriel-p** [comment]
Yes very much this! 'Actions' should be below 'Settings'

**Comment by dagolinuxoid** [comment]
`sudo apt remove appcenter` there u have it
