### ISSUE TITLE
If I want to display the time and date on the right, what code do I need to modify?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [elementary/applications-menu#165]
How to put the date and time on the right

**Comment by peteruithoven** [comment]
What date and time? Could you share a screenshot? You mean in the Wingpanel (top panel? Where it's normally in the center. 
You could have a look at the [Wingpanel](https://github.com/elementary/wingpanel). I see some relevant code here: https://github.com/elementary/wingpanel/blob/master/src/Widgets/Panel.vala

But this is the repo for the Applications menu, which is probably not related to your question, and your question isn't really an issue, so I'm closing this one.

**Comment by Yakumo-Yukari** [comment]
@peteruithoven Thank you
