### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [elementary/applications-menu#183]
```
Build type: native build
Project name: slingshot
Project version: 2.4.2
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Native Vala compiler: valac (valac 0.40.13)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Dependency glib-2.0 found: YES 2.56.3
Dependency gee-0.8 found: YES 0.20.1
Dependency gio-2.0 found: YES 2.56.3
Dependency gtk+-3.0 found: YES 3.22.30
Dependency granite found: NO (tried pkgconfig)

meson.build:25:0: ERROR:  Dependency "granite" not found, tried pkgconfig
```

**Comment by peteruithoven** [comment]
Install `granite?`
```
sudo apt install elementary-sdk
```
or more specifically:
```
sudo apt install libgranite-dev
```

**Comment by Yakumo-Yukari** [comment]
> Install `granite?`
> 
> ```
> sudo apt install elementary-sdk
> ```
> or more specifically:
> 
> ```
> sudo apt install libgranite-dev
> ```

thank you for your help

**Comment by federicomartinlara1976** [comment]
Install elementary-sdk:

E: No se ha podido localizar el paquete elementary-sdk

Installing libgranite-dev:

meson.build:26:0: ERROR: Dependency "elementary" not found, tried pkgconfig and cmake

The solutions above are not useless.

**Comment by N3koSempai** [comment]
> Install elementary-sdk:
> 
> E: No se ha podido localizar el paquete elementary-sdk
> 
> Installing libgranite-dev:
> 
> meson.build:26:0: ERROR: Dependency "elementary" not found, tried pkgconfig and cmake
> 
> The solutions above are not useless.

dont use:
```bash
sudo apt install libgranite-dev
```
try:
```bash
sudo apt-get install libgranite-dev
```
and the same for elementary-sdk

**Comment by jeremypw** [comment]
Try `sudo apt build-dep slingshot-launcher`

**Comment by boulabiar** [comment]
nothing cited here works

**Comment by danirabbit** [comment]
Required build dependencies are listed in the README. You'll need to install packages according to your package manager
