### ISSUE TITLE
Document Viewer absent from the Applications Menu

### ISSUE THREAD

**Issue by uncertainjatan** [elementary/applications-menu#188]
As I understand it, elementary wants to promote app-based navigation and interaction of files, Photos for viewing and managing pictures, Music for songs, and so on.

In that case, shouldn't the PDF/Document reader be visible upfront in the applications menu? It only becomes apparent on searching the menu. It's default window is also quite useful to consider this change as it lists all recently opened documents, something that seems very elementary-like.

**Comment by worldofpeace** [comment]
Looking at https://github.com/elementary/applications-menu/blob/8e64deba5340a4500c2198c77b4eba273e45b7a0/data/pantheon-applications.menu

evince is purposefully excluded and so is gnome-font-viewer, file roller, etc. 

Perhaps the idea is they'd want native apps for those purposes?
But I don't think that should come to hiding needed applications.

**Comment by uncertainquark** [comment]
Evince is a native app. And yes, it should not be hidden even if it wasn't, because it is a useful app.

**Comment by worldofpeace** [comment]
Native as in the elementary project produced it and with their HIG in mind.

**Comment by uncertainquark** [comment]
Ah, okay. But it's being shipped as default and elementary doesn't produce any replacement, so it should be visible in the app menu.

**Comment by D0J0P** [comment]
I think the solution would be for elementary to replace Evince with their own document viewer that adheres to their own HIG, rather than having an extraneous app built-in. I think evince and the font viewer are probably the only GUI apps left in eOS that aren't really native apps if I'm correct.

**Comment by Pardaigle** [comment]
I can see the document viewer in the application menu on elementary Hera with no custom configuration.
Maybe this issue could be closed ?

**Comment by uncertainquark** [comment]
I still don't see it. It only appears in search but not as an app icon in the menu. I also tried uninstalling and reinstalling.

**Comment by danrabbit** [comment]
Utility apps were hidden to avoid cluttering the menu. It's probably worth revisiting some of these to see if it  still makes sense or is still relevant. Adding this as a discussion item for the 6.0 milestone
