### ISSUE TITLE
Close popover when Uninstalling app

### ISSUE THREAD

**Issue by cassidyjames** [elementary/applications-menu#189]
Right now secondary-click → uninstalling an app leaves the popover open while the polkit dialog opens, then after the app is uninstalled the popover inelegantly reloads without the app. Instead, I think it would make sense to close the popover upon selecting the Uninstall action.

**Comment by danrabbit** [comment]
I feel like I would be more inclined to make removing the app nicer/more immediate. I’m not sure that removing an app means I’m necessarily done

**Comment by cassidyjames** [comment]
@danrabbit well we have to throw a polkit (or at least confirmation) dialog, and having dialogs open with WingPanel indicator popovers open can get weird due to the whole fake fullscreen window thing (if you alt+tab, for example). We typically close popovers when they lose focus, and in this case the popover no longer has focus but is staying open.
