### ISSUE TITLE
Apps are not in focus after launching from application menu

### ISSUE THREAD

**Issue by uncertainquark** [elementary/applications-menu#19]
It doesn't always happen but when it does, the app that is just launched is not brought into focus for input. This means for example, in AppCenter, launching it and starting to search doesn't work. 

It can only be tested by setting up hot corners. Say set top right as "Maximize current Windows", then launch Photos app and try to move cursor to top right. The window in the background is maximized/unmaximized instead.

**Comment by peteruithoven** [comment]
I'm also not sure which aspect of Elementary OS would be responsible for this, but you made the same post here: https://github.com/elementary/gala/issues/1.

**Comment by peteruithoven** [comment]
Seeing that https://github.com/elementary/gala/issues/1 was closed, shouldn't we also close this one?

**Comment by peteruithoven** [comment]
To clarify this is about focus, not whether a window is shown on top.
It doesn't matter whether the app is opened from search results or by clicking on an app in the grid. 
I can reproduce the issue with Calculator, Terminal, Files, System Settings etc. 

In the recording below you'd expect the focus to go to the newly launched Terminal, but it's returned to the Calculator.
![screen record from 2019-01-24 22 42 41](https://user-images.githubusercontent.com/523210/51710434-7d554900-2029-11e9-92c4-e58f59979357.gif)

This almost seems like something manually returns (overrides) focus to the previously focused app when the applications menu is closed.

**Comment by peteruithoven** [comment]
This might actually be handled by the wingpanel: 
https://github.com/elementary/wingpanel/blob/master/src/PanelWindow.vala#L157-L162
https://github.com/elementary/wingpanel/blob/master/src/Services/BackgroundManager.vala#L80-L102
https://github.com/elementary/wingpanel/blob/master/wingpanel-interface/FocusManager.vala#L34-L51

**Comment by peteruithoven** [comment]
I think we've figured out the underlying issue: https://github.com/elementary/wingpanel/issues/205
I've opened a PR: https://github.com/elementary/wingpanel/pull/206
