### ISSUE TITLE
Make 'Web Applications' created with Epiphany removable

### ISSUE THREAD

**Issue by J0Ar** [elementary/applications-menu#20]
It would be nice if there would be a 'right-click' option to remove the 'Web Applications' created by Epiphany. At the moment you only can remove those by deleting the specified .desktop-file in 
~/.local/share/applications/

Thanks J.Ar :)

**Comment by cassidyjames** [comment]
My guess is that this would be up to the app that created the .desktop entry; just letting Slingshot arbitrarily remove entries means for other apps people might think they're uninstalling the app, but the app remains without a way to easily see that.

Instead, I imagine Epiphany would need to provide a desktop action that is "Remove web app" or something that removes the .desktop entry and also performs any needed cleanup.

**Comment by J0Ar** [comment]
You are right, Cassidy. 
 I just found out, you can remove the Web Applications by typing **about:applications** in the adress bar. It's documented in the Help of Epiphany. 
![screenshot from 2017-05-29 18-23-11](https://cloud.githubusercontent.com/assets/23266409/26556731/93ebae4e-449c-11e7-96d0-7d7830e9a288.png)

**Comment by J0Ar** [comment]
Maybe there is a way to show those 'Webb apps' in Appcenter and make it like the other installed apps...?

Right click on WebApp > Uninstall/Remove > Appcenter shows up > Uninstall/Remove the WebApp

There is a way with '(Gnome)Software' too i see in the screenshot.
So, maybe a clever developer can implement this...if people would like to have it^^

**Comment by SubhadeepJasu** [comment]
AN easy way would be to put a "Uninstall Web App" option in the epiphany menu that launches about:applications in a new tab.

**Comment by cassidyjames** [comment]
@SubhadeepJasu again, that would be up to Epiphany to add an entry to the created .desktop file. 

An alternative proposal would be to allow the removal of any launcher in the _user's_ applications folder. These are likely to be created by apps like Chrome or Epiphany and not have an intuitive, built-in way to remove them.

**Comment by raibtoffoletto** [comment]
I think this should be an issue in Epiphany's bug tracker. I'd prefer to have this option in the drop down menu of the application, together with preferences.

**Comment by cassidyjames** [comment]
I've reported this upstream: https://gitlab.gnome.org/GNOME/epiphany/issues/958

**Comment by janxkoci** [comment]
> AN easy way would be to put a "Uninstall Web App" option in the epiphany menu that launches about:applications in a new tab.

This option is present in newer versions of Epiphany - I have a menu item called "Manage web applications" in 3.32 from snap package. Sadly webapps don't really work in snap. :disappointed:
