### ISSUE TITLE
Add Fullscreen view

### ISSUE THREAD

**Issue by linuxrx01** [elementary/applications-menu#205]
Hello, is it possible to add Fullscreen view like Apple?

![image](https://user-images.githubusercontent.com/49744994/59211886-4b481c00-8bb1-11e9-82dd-fc78edf86c4f.png)

Thank you!

**Comment by cassidyjames** [comment]
Original versions of Slingshot were actually full screen, but we found with user testing that a smaller paged grid performed much better and redesigned it. As such, I'm closing this as a design conflict.
