### ISSUE TITLE
Can't uninstall .Deb programs downloaded from the internet

### ISSUE THREAD

**Issue by D0J0P** [elementary/applications-menu#228]
Programs like Vivaldi downloaded from vivaldi.com as a .deb file, opened and installed with Eddy doesn't seem to have the "uninstall" feature in the context menu.
![Screenshot from 2019-07-30 23 35 04](https://user-images.githubusercontent.com/19495660/62181909-d9738f80-b322-11e9-8a20-ce2d3358ff7b.png)

Every other program, like those downloaded from AppCenter, are fine. I haven't tested this with flatpaks or snaps though.

**Comment by cassidyjames** [comment]
There's actually no standard that I know of to track which icon belongs to which package, other than via AppData. If we have AppData, it appears in AppCenter and thus gets an uninstall item here. I think this is a case where I have to close as out of scope. :(
