### ISSUE TITLE
Custom Application Launcher uses xterm instead of io.elementary.terminal

### ISSUE THREAD

**Issue by queeup** [elementary/applications-menu#232]
Applications with "Terminal=true" key are searching xterm to execute. If xterm not installed on the system, app menu can not execute that application.

*Reproduce:*
- Open App menu
- Search htop
- Chose and try to execute htop

*Dirty fix:*
```
ln -s /usr/bin/io.elementary.terminal /usr/bin/xterm
```

#### Need gnome patch like mate team did:
- https://gitlab.gnome.org/GNOME/glib/merge_requests/795
#### Related lines:
- https://gitlab.gnome.org/GNOME/glib/blob/master/gio/gdesktopappinfo.c#L2520

**Comment by danrabbit** [comment]
Since this seems to be an issue in GLib, I'm closing this as "Out of Scope" for the applications menu

**Comment by queeup** [comment]
So, who is going to report to GLib? I think elementary OS developers should report or help GLib to fix this.

**Comment by danrabbit** [comment]
@queeup The issue is already reported here: https://gitlab.gnome.org/GNOME/glib/issues/338

**Comment by queeup** [comment]
Yea I know. 9 years without fix. Better to find workaround then wait for fix, if you ask me.
