### ISSUE TITLE
Feature request - Editing the menu items

### ISSUE THREAD

**Issue by iXecFTW** [elementary/applications-menu#25]
- It would be nice if there was a way to edit the menu items by right clicking them. (change the name, icon, hide)
- Maybe add drag&drop so you can easily put them in a different category too.

**Comment by danrabbit** [comment]
I'm going to close this as a "won't fix". If you feel the need to change a .desktop file, you should report that as a bug to the developer of the application

**Comment by iXecFTW** [comment]
Fair enough

Just have some google chrome shortcuts that are in the 'other' category. (Like Netflix, Gmail, etc)
Thought it would be a nice to sort them.
