### ISSUE TITLE
Add "View in AppCenter" action to context menu

### ISSUE THREAD

**Issue by cassidyjames** [elementary/applications-menu#31]
This is open to discussion, but it might

1. ~Be more honest about what the action does (since it doesn't automatically kick off an uninstall), and~ _It does prompt for uninstall in slingshot master_

2. Serve as a handy way to get users back to the AppCenter listing if they are looking for more info (i.e. in lieu of an About dialog)

**Comment by btkostner** [comment]
Also somewhat related, but this should be in the right click menu as well. It should also _never_ appear first when searching for the app name.

**Comment by cassidyjames** [comment]
@btkostner that's where this action already is; it's not a result in the search.

**Comment by danrabbit** [comment]
The uninstall item doesn’t open AppCenter currently. I think this should be a new, additional item

**Comment by cassidyjames** [comment]
Ah yeah that's also cool with me; I wasn't on Slingshot master so I was just seeing it open the app's page in AppCenter.

**Comment by alex285** [comment]
i was just about to open this issue! please add a "Show in App Center" on right menu! it is super super handy if we want to see some additional info, like changelogs, and projects pages
