### ISSUE TITLE
Missing Size Settings

### ISSUE THREAD

**Issue by AtjonTV** [elementary/applications-menu#328]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I have been using ElementaryOS for over 2 years now, and since a year I am using Elementary Tweaks to set my Launcher to `9x6` (9 Columns by 6 Rows), so that I can see most of my applications at once.

Since the update to 2.5.0 the size is back to 5x3 (5 Columns by 3 Rows), and I dislike the Launcher being so tiny.

I found a [PR that removes this](https://github.com/elementary/applications-menu/pull/267), but the reason is stupid.

### To Reproduce
1. Install Applications-Menu 2.5.0
2. Set Colums and Rows in the glib schema file
3. Look at the tiny mess

### Expected behavior

When I set a Custom size, I want to have a custom size.

## Platform Information
![image](https://user-images.githubusercontent.com/24845056/70039914-ecd98480-15ba-11ea-9bcd-04219d4b01e2.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context

I tried to compile Slingshot from source, but for what ever reason I cannot install GTK+-3-dev as it collides with ~100 other packages.

I basically rely on someone to provide me a debian package.

Also, I cannot find a debian package for the prior version of Slingshot that would bring back what I loved.

**Comment by AtjonTV** [comment]
I managed to build Commit 8263d1d6d9a32cdb4fc914b7a981619644a56170 using a Docker Container.

From the container I just extracted the `libslingshot.so` file and replaced the one on my System. After adding Screen Resolution settings to the glib schema, it is now working as it should.

It is nice to see Elementary being developed further, but just removing features user may depend on, and not mentioning it in the release notes is aweful.

From now on, I will check each individual part of Elementary that was updated before I install it, to prevent this from happening again.

I love ElementaryOS, but this action now cost you all blind trust I had.

-----

This issue may be closed now, unless you guys feel the need to actualy fix this "issue" in upstream Slingshot.

I will now go and Fork Slingshot, revert the offending commit and rebuild it for my use.

**Comment by supernoi** [comment]
I also missed the feature to edit the menu size (columns x lines).

**Comment by nnmlss** [comment]
> I managed to build Commit [8263d1d](https://github.com/elementary/applications-menu/commit/8263d1d6d9a32cdb4fc914b7a981619644a56170) using a Docker Container.
> 
> From the container I just extracted the `libslingshot.so` file and replaced the one on my System. After adding Screen Resolution settings to the glib schema, it is now working as it should.
> 

Can you share `libslingshot.so`, because it is a real problem for me also. I have 50+ apps installed and I find it really disturbing to scroll back and forth 5x3 grid using 1/6 of my screen space to find the app I need..

**Comment by AtjonTV** [comment]
@nnmlss 

I created a small guide that shows how to manually install the latest version of Slingshot where the size feature was patched back. As well as adding a Elementary-Tweaks version that still supports this feature.

The Guide can be found here: [https://beeit.org/eos-hax](https://beeit.org/eos-hax)

The Binaries are at their repositories on the [ATVG-Studios](https://github.com/ATVG-Studios) group Forks, placed at the latest Release.

**Comment by danrabbit** [comment]
We’re working through some major rewrites to improve performance and this key was removed because it was never exposed to users and there was code to automatically overwrite its contents based on display resolution.

Once new grid view code is in place, we can look at supported grid and possibly icon size settings. But the way it was done was stopping work on other parts of the code base.

In general, gsettings should not be considered stable API.

**Comment by isantop** [comment]
> I have 50+ apps installed and I find it really disturbing to scroll back and forth 5x3 grid using 1/6 of my screen space to find the app I need..

You should probably be using search to get directly to the app you're looking for. It's much faster than trying to manually find the app in the list anyway.

**Comment by nnmlss** [comment]
> You should probably be using search to get directly to the app you're looking for. It's much faster than trying to manually find the app in the list anyway.

If I use the keyboard - yes, slingshot works really well! But what if I use only a mouse? Or a tablet? And.. do you think that I remember all the names of the apps I use? No, I don't.  Some of them are just abreviatures. But I remember their icons. It is not a question of 'is it faster or not' but 'is it easy or not'. 

Big resprect to the elementary OS crew for the work you do to make the OS so nice, clean, good looking and really light on resources. I hope eOS will not be usefull only for the coders.

**Comment by Exalm** [comment]
But... You probably put the apps you frequently use onto dock?

**Comment by AtjonTV** [comment]
If I put all the apps I frequently use in the dock, it fill the whole screen with and leave some out.

I have lots of tools installed, like 10 different Webbrowsers, 8 IDEs and much more. I would guess 70+ UI apps.

With 9x6 I have 4 pages. With 5x3 I have 10.

I also mainly search for Icons as I can't remember all names of the apps when being busy in work.

**Comment by nnmlss** [comment]
@AtjonTV  I cannot make it work following your guide. In the place of screen_resolution key I have tried both "1920x1080" and "1920x1080_60" with no success - the slingshot remains 5x3 grid.  Which syntax is correct?

**Comment by AtjonTV** [comment]
@nnmlss just keep the resolution empty .. that works for me

**Comment by cassidyjames** [comment]
Closing since @danrabbit has addressed the reasoning, and there's not really anything specifically actionable with this issue report. But y'all are welcome to continue to discuss things here or elsewhere.

**Comment by AtjonTV** [comment]
If anyone needs help following my guide, you can join my public matrix channel: https://matrix.to/#/#public:matrix.atvg-studios.com
