### ISSUE TITLE
Up key does not focus search at top of CategoryView

### ISSUE THREAD

**Issue by cassidyjames** [elementary/applications-menu#344]
Originally reported here: https://github.com/elementary/applications-menu/pull/329#pullrequestreview-331197550

>There is an inconsistency between GridView and CategoryView in that the Up key returns focus to the searchbar in the former case but not the latter. However, this can be dealt with in future PRs cleaning up keyboard handling.

**Comment by danrabbit** [comment]
I'm going to reopen this since as Jeremy pointed out, there's still an issue when trying to navigate up from the category sidebar
