### ISSUE TITLE
Applications Menu ， It can't be opened after startup。

### ISSUE THREAD

**Issue by Yu-Xiao-Sheng** [elementary/applications-menu#345]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug

If applicable, add screenshots or screen recordings to help explain your problem.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by IT-Tool** [comment]
Duplicate of #393

**Comment by ryonakano** [comment]
I'll close this as a duplicate of #393. Reopen and provide more information if it's not.
