### ISSUE TITLE
application menu dissapeared

### ISSUE THREAD

**Issue by meyash** [elementary/applications-menu#347]
![Screenshot from 2020-03-03 21-40-48](https://user-images.githubusercontent.com/21121279/75795005-ab15d100-5d97-11ea-9cfd-85ef4449bc6f.png)

**Comment by vjr** [comment]
Can you run the following commands in a terminal? If you can open a terminal in the first place :-)

`killall wingpanel` then `wingpanel`

**Comment by meyash** [comment]
> Can you run the following commands in a terminal? If you can open a terminal in the first place :-)
> 
> `killall wingpanel` then `wingpanel`

It worked👍
