### ISSUE TITLE
Change 'applications' text into an icon

### ISSUE THREAD

**Issue by VisioFX** [elementary/applications-menu#35]
I love minimalistic designs, so would really love to see an icon instead of the current 'applications' text.
Or perhaps even a feature to customize it, as some people may prefer both icon and text.

Perhaps this feature is somehow already available, yet I was unable to find it.

**Comment by cassidyjames** [comment]
An icon would very likely be less clear than a word, so I don't think we're planning to change this.

**Comment by waldyrious** [comment]
For those interested, there's a project to implement this change as a workaround: https://github.com/nightsense/elementary-panel-logomark (/cc @nightsense)
