### ISSUE TITLE
White Icons are near invisible

### ISSUE THREAD

**Issue by rasmus91** [elementary/applications-menu#352]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Mostly white icons tend to 'dissapear' in the applications launcher.  (look at the Gnome Boxes Icon)

![billede](https://user-images.githubusercontent.com/2297739/77055778-cb69a080-69d1-11ea-8dab-5e536a6782b9.png)

**Describe the solution you'd like**
I'm not quite sure how this could be solved, but I imagine we could look at the composition of the image, and then create a soft shadow or something behind it. This will create some contrast for the icon. But it should be done carefully, or it will easily look coarse and unrefined

**Existing work**
I don't know that this already exists. But elementary OS does already react in someways to the colors of the background.

**Comment by danrabbit** [comment]
@cassidyjames

**Comment by rasmus91** [comment]
Thank you for taking the time to reply. I had not thought of it that way.

The app developers can never know if they are developing for someone with a dark or light theme (and so on), so I guess the icon should be designed accordingly. 

However: I think it's a bit of a slippery slope either way, on the one hand the icons have to be well designed, on the other they can't possibly be accounting for every possible environment they may be used in. And while curated apps should certainly cater to elementary OS and the Pantheon desktop in every way, I think most people have to run non-curated apps at times, meaning they may run into this. At the same time, you're absolutely right: it is *unreasonable* to expect you to present every third-party app nicely.

Anyhow, it was just a thought I had, and I'm just putting it out there 🙂
And I actually somewhat like the icon, oh well.

**Comment by cassidyjames** [comment]
Yeah the problem here is GNOME apps are designed explicitly for the entire OS to put some sort of a shadow behind the icon, but that doesn't look good with every (especially non-GNOME) icon. If GNOME apps are being used on non-GNOME platforms, they probably need to address this in the apps/design language.
