### ISSUE TITLE
How do I update ? Freaking spores in the works

### ISSUE THREAD

**Issue by capwalker** [elementary/applications-menu#355]
Seems that an update (APT UPDATE) will shut down at i-hate-farms in the elementary-tweaks app with invalid signature. Now being just under a week familiar with linux versus os x, it's hard navigating your supporting structure. I';ve triewd everything that's been suggested, even read the neat article explaining the apt system, but still hit the wall on this. And my system is still unstable.

Usually this requires a reinstall. Great, but I'm also creating a grand reinstall script to automate the hours I've spent customizing it.

I'd appreciate any help before I have to bite the bullet.

**Comment by jeremypw** [comment]
Which version of elementary are you using? You may need to uninstall the spores ppa and elementary-tweaks if they are not compatible with that version.

**Comment by capwalker** [comment]
I tried. How (what commands) would you do it ?

   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by jeremypw** [comment]
To uninstall elementary-tweaks from the command line (Terminal) type `sudo apt-get purge elementary-tweaks`.  Or you could install Synaptic, search for elementary-tweaks and then uninstall using the context menu (Right-click, Mark for complete removal).  

I am not sure how you installed the spores repo - grin GitHub? If so I guess to remove it in Terminal `sudo add-apt-repository --remove "deb http://i-hate-farms.github.io/spores trusty main".  Note that elementary is currently based on bionic not trusty (which might be part of the problem).  If you got the repo elsewhere you might need to change the URL in the above command. Otherwise you can use Synaptic/Settings/Repositories and disable or delete the relevant repo.

**Comment by jeremypw** [comment]
Note that it is really not recommended to install non-curated 3rd party software unless you know what you are doing.

**Comment by capwalker** [comment]
Unless I straight installed the tweaks straight, I've no idea either. Me
have the repo ? my only repo was when I tried hiding the car... I'm trying
to follow how to use Synaptics. This is my second week with Elementary, put
some years with OS X. And started in '84 supporting a programmable word
processor called Sprint for a MS Competitor called Borland (rbg).


   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by capwalker** [comment]
Now see how messed up I am.

How do I get to synaptic ?



   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by capwalker** [comment]
yes, i know, but sometimes it's the best way to learn.

libdvd-pkg: `apt-get check` failed, you may have broken packages.
Aborting...

so the purge won't work. and it should. And it's times when things don't
work like they should is when I learn I don't know what I'm doing. But,
it's what it's all about, no ?

Aha!!! Synaptic was the answer to the questions I didn't know I had. I try
that and will get back if further questions.

   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by capwalker** [comment]
Unfortunately Synaptic fails in two critical areas

1) reports NO unbroken packages
2) The script file to create a new system with all items installed as
before does NOT install each separate items. For instance, neither ATOM or
SUBLIME are set to be reinstalled.


   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by tintou** [comment]
It seems that you've altered the system in a way that you don't truly understand, this is the reason why we don't recommend adding PPAs. This issue has nothing to do with the Applications menu. Closing it. For community support, please see the elementary OS Stack Exchange : https://elementaryos.stackexchange.com/

**Comment by capwalker** [comment]
No I don't YET. And I won't ever when trolls like you suffer premature
control issues. Jeremy and I were doing just fine. So, I'll just keep
opening a new question. How much effort will you waste when all you needed
to do is abide by teh rules of respect and patience.

   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by jeremypw** [comment]
@capwalker Tintou is correct,really, and it doesn't help to call a key elementary developer a 'troll'.  You would probably get more eyes on your issue on Stack Exchange, including users who have also installed the same 3rd party software as you - it is not something an elementary dev is likely to do.  You could also raise an issue here: https://github.com/I-hate-farms/spores/issues  Hopefully the developer of that software will be willing to help.

So what was the ouput from the two terminal commands I mentioned above?

**Comment by capwalker** [comment]
Actually Jeremy, I'm a key developer in another area and had been an
internet sysop in a rather large forum for 12 years before retiring ou of
it. I got too tired of teaching children how to play well with others like
we just witnessed. Not sure 'Tintou' as I'm in gmail replying, however,
your messages have been exactly what I'm hoping for. Someone else might
take a different tack, but I'm learning much better the way you're handling
it. ;' The Synaptic package manager is almost what I need. Neither truly
fix the problem in that Synaptic reports no issues. Right now I'd like two
things out of this problem :
1) Learn why gEdit and extract manager put me in a second selection screen
yet don't allow me to choose then proceed
But #1# is a side issue
2) Get Synaptic to generate a script that would take a virgin install, no
additions, changes, etc. and change it to what I have now. Then I'll just
plain reinstall. I try removing, updating, you name it. I just don't see
progress.

   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by jeremypw** [comment]
Synaptic does have a "Generate Package Download Script" option under the "File" menu (although I have not used it personally) - I just have a long `sudo apt install X Y Z ....` statement recorded in a text document along with other modifications e.g. to fstab I make.  I do not know of an app available for recording and reinstating wide-ranging config changes automatically.

**Comment by capwalker** [comment]
I noticed that Generate Package Script and got excited until I looked
deeper. Seemed as if it only does that for what's selected. I need it to
generate that long sudo apt install script like you have. I really don't
look forward to creating a script for everything I've done.

I can't figure out how to use Synaptic to uninstall Elementary-Tweaks. That
is I know  to search for and then uninstall it, but it's not there. It
still reports that repository problem. This doesn't make sense to me. Seems
I can't get a proper upgrade due to it, but I can't remove it either. No
doubt I'm not explaining it well.

   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by capwalker** [comment]
Output to first try:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package elementary-tweak

It couldn't be found in Synaptic

Under the third try ('remove') I get a '>' prompt

I was so frustrated I didn't slow down and go step by step like I should
have. So I ran through these messages after everything settled and the
machine was powered off all night.

Also, you (and the troll) assumed _I_ actually knew the different installs.
I wish (lol) I literally had been combing through catalogs of 'neat'
programs to add and ran across this tweaks program and read how it said to
install it and report problems. Speaking of neat programs, any idea how to
run Sublime Text in demo mode ? My download asks for a license and I'm not
paying $80 yet. I'm going to try ATOM for a while.

I just tried APT UPDATE after all teh above attempts. It still shows :

W: GPG error: http://i-hate-farms.github.io/spores trusty InRelease: The
following signatures were invalid: 2F3C3D45B6C9A4E9E22A1AE1F7F707E5B5329C31
E: The repository 'http://i-hate-farms.github.io/spores trusty InRelease'
is not signed.
N: Updating from such a repository can't be done securely, and is therefore
disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration
details.
E: The repository '
http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu bionic
Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore
disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration
details.

I'm going to try INSTALLing it again through Synaptic and then removing.
Making sure to shut down in between. I'm sure this will date me, but LINUX
seems like an overgrown version of CP/M. All these procedures that a
regular OS hides. Even DOS (Apple and IBM) doesn't require as much.

   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by capwalker** [comment]
Let me step back. As one sysop to another, taking a drastic step as cutting
off a discussion without prior warning and full understanding is a newbie
mistake and will get you plenty of reactions like you got from me. A less
drastic sysop action would be to MOVE rather than close the discussion.
Clearly it was a discussion rather than a single sided thread. With your
Sysop powers comes more than power to move threads or close them. There's
the responsibility to be clear, to foster learning and promote
understanding. All things which UNILATERAL action, even justified, defeat.

   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by capwalker** [comment]
The hyperlink isn't appropriate. It assumes a completely different context.
What would have been more appropriate is some area where those
transitioning from other oses can post about documentation and beginning
attempts at administrating a system.

   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by capwalker** [comment]
I'm at a loss on how this UI is acting. In a few apps I'm taken to what
looks like a GUI for traversing the file system tree. But there's
nowhere to designate the final directory (to create the file, or extract)
or especially in a file. save as, be allowed to designate the file name. Do
you need a more exact example or is that enough to be familiar ?

   1. inessuno è cieco come coloro che rifiutano di vedere

**Comment by jeremypw** [comment]
The correct package name is `elementary-tweaks` (plural) You may have mistyped it? 

Thats the problem with installing non-curated 3rd party stuff - it may not be easily uninstallable (and may not be visible in Synaptic). :-(  In the long run you may be better off making a note of the extra apps you installed then reinstalling _from the official iso_ available here https://elementary.io/ , especially if you are unfamiliar with Linux.  

I am sorry I have not been able to help you as you hoped - I tried my best - I am just a volunteer not a professional sysop.  There isn't anywhere on github/elementary where it would be more appropriate move this but I suggest trying https://elementaryos.stackexchange.com/ where a wider range of people are available to answer.  I monitor that site mainly for questions on pantheon-files.

You should create a separate thread for each unrelated question you have I am afraid as different people may be best to answer.
