### ISSUE TITLE
Grid view: erratic keyboard navigation

### ISSUE THREAD

**Issue by mcclurgm** [elementary/applications-menu#388]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Navigating the grid view using the keyboard has some odd selection behaviors. It seems like the last selected element is saved when the grid view loses focus. Navigating back to it selects the first element in the current grid always, but then as soon as I use an arrow key to select a different app it moves as if it had a different app selected. I'm not sure how to describe this well, so I'll just give an example:

### To Reproduce
1. Open the grid view. Don't type anything.
2. Using the arrow keys, select an app in the middle of the grid (say, the third element from the left in the middle row).
3. Type to start a search. Delete all text to return to the grid view.
4. Press the down arrow key to select a grid item. It will be the top left item.
5. Press the right arrow key. The fourth element from the left in the middle row will be selected.

### Expected behavior
In step 5, I expect that it will select the second item from the left in the top row, since that's the item immediately to the right of the current selection.

Note, this behavior still happens when I close the applications menu and then reopen it. Instead of typing in step 3, I can close and reopen the menu (for my setup, press the super key twice) and the same behavior will happen in steps 4 and 5.

## Platform Information

![about](https://user-images.githubusercontent.com/29022469/82155574-1d447080-9833-11ea-9e9e-f9ee3cd6f07b.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by hanaral** [comment]
Yeah I see what you mean, it seems that the logic that reselects the last selection after typing is off.

**Comment by Blast-City** [comment]
I can also replicate this issue the following way:

1- Open the applications menu.
2- Press Down two times.
3- Press Esc to close the applications menu.
4- Open the applications menu again.
5- Press Down two times.

**Result:** Instead of going to the second row, it goes to third one skipping the second. The only way to recover the normal behaviour again is by killing the Wingpanel process.
