### ISSUE TITLE
Scrolling in grid view only scrolls per one page

### ISSUE THREAD

**Issue by donadigo** [elementary/applications-menu#396]
Scrolling in grid view with the mouse wheel will always scroll by one page, ignoring how many scroll steps there actually were. With this behaivour scrolling to the last page gets very tedious when the scroll only works for one page at a time. This should be fixed in #395.

**Comment by cassidyjames** [comment]
Is this something that can/should be handled in LibHandy, or is it something we can still address here? 

cc: @Exalm @danrabbit in case you know. :smile:

**Comment by danrabbit** [comment]
Yeah I think if this can still be reproduced then it's now a Hdy issue

**Comment by cassidyjames** [comment]
Still can be reproduced here with a mouse.

**Comment by danrabbit** [comment]
We don't do any custom scroll event handling here, so "out of scope" :)

**Comment by Exalm** [comment]
It is in libhandy, yes. There's a timeout to prevent uncontrollably fast scrolling (see https://gitlab.gnome.org/GNOME/gnome-shell/issues/1338, same thing), if you have better ideas, issues/MRs welcome :)
