### ISSUE TITLE
Make app-launcher faster

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/applications-menu#403]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

It shows noticeable lag compared to other launchers. [ULauncher](https://ulauncher.io/) for example is almost instantaneous

**Describe the solution you'd like**

A faster app-menu?

**Comment by danrabbit** [comment]
Hey thanks for filing an issue report. As written, there's not really anything actionable we can do here. It's not really clear when we could make this issue as closed. Of course we always want things to be faster, but without a more specific issue I'm inclined to close this report as "incomplete".

If you can provide more information about a specific scenario that causes a performance issue (such as during the first minute after startup or a relationship between speed of opening and number of pages of apps) then we could take action on that issue
