### ISSUE TITLE
Calculator plugin: Method of copying the result not easily discoverable

### ISSUE THREAD

**Issue by jeremypw** [elementary/applications-menu#412]
I have searched open and closed issues for duplicates.

## Describe the bug
The result given by the calculator plugin cannot be selected or copied (at least, the obvious methods do not work), limiting its usefulness.

### To Reproduce
1. Open the Applications Menu
2. Type a calculation in the search bar
3. The result appears in the app list , next to the calculator icon
4. The result cannot be selected or copied with the keyboard shortcut when the line is focused.  Activating the line appears to do nothing (calculator does not open) but in fact the result is copied to the clipboard.

### Expected behavior
Some indication of how to copy the result should appear e.g. as a placeholder or in the tooltip.

![image](https://user-images.githubusercontent.com/10513844/92235760-245bc100-eeac-11ea-8288-6018a5210fe6.png)

- [x] I'm using the latest Odin version

## Additional context
Running a VM

**Comment by cassidyjames** [comment]
Appending something to the result might make sense, like

**12345** - Select to copy result to clipboard

**Comment by jeremypw** [comment]
That could work except "select" is somewhat ambiguous in this context. It could mean "select the text" - which is what I initially tried to do.  I only discovered by chance that pressing enter or clicking on the item copied the answer to the clipboard as well as closing the menu.

**Comment by Eldhrimer** [comment]
I was looking bitsized issues to fix and this appear to be already fixed. This issue should be closed.

**Comment by jeremypw** [comment]
Thanks.  The PR was not properly linked to this issue so it did not automatically close.

**Comment by ryonakano** [comment]
Unpinning since this issue has been already fixed.
