### ISSUE TITLE
Calculator results only show whole numbers when dividing

### ISSUE THREAD

**Issue by cassidyjames** [elementary/applications-menu#414]
For example, `5/2` should show `2.5`, but it clamps to `2`.

**Comment by jeremypw** [comment]
I cannot confirm this using the master source - I get 2.5 after entering `5 / 2`.

**Comment by jeremypw** [comment]
Not sure of the utility of this plugin - but should probably use the existing calculator app anyway (which does not suffer this issue).  It feels wrong to have two different native calculators.  If the calculator app had a commandline interface that accepted a string to parse and evaluate then it could just be launched to provide the answer.

**Comment by jeremypw** [comment]
This is a regression due to https://github.com/elementary/applications-menu/commit/058a0c31db352a222d17ef1d53b87f7c94e5593a

**Comment by jeremypw** [comment]
Mea culpa - I approved that PR :disappointed:  Pushing a PR to reverse the relevant part.
