### ISSUE TITLE
Context menus are not shown with proper height

### ISSUE THREAD

**Issue by ryonakano** [elementary/applications-menu#423]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
![Screen record from 2020-10-07 11 47 15](https://user-images.githubusercontent.com/26003928/95281793-f2ff5800-0892-11eb-93e2-0f00972d42bd.gif)

The "Uninstall" and "Show in AppCenter" menu entry in the context menu of an app icon is not shown by default and need to scroll on the menu.

### To Reproduce
1. Open Applications Menu
2. Click on some app e.g. Files, AppCenter, Calcurator, or curated apps like Reco, LookBook, etc.
3. See "Uninstall" and "Show in AppCenter" is not shown by default
4. Scroll on the context menu. "Uninstall" and "Show in AppCenter" appears

### Expected behavior
All context menu entries should be shown by default without scrolling.

## Platform Information
- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version
- [x] I'm using the latest daily version

**Comment by cassidyjames** [comment]
Whoa, that's wild. This must be a pretty recent change, and I can confirm it here.

**Comment by ryonakano** [comment]
Hmm, I also face this issue in context menus in some other apps, e.g. Files:

![2020-10-12 10 32 37 の画面録画](https://user-images.githubusercontent.com/26003928/95696500-5532d100-0c76-11eb-8444-5b2472468728.gif)

Might be a GTK or stylesheet issue?

**Comment by jeremypw** [comment]
I do not think this part of the code has changed so looks like a side-effect of some upstream change. I'll see if there is a fix.

**Comment by jeremypw** [comment]
I havent found a fix by tweaking the Gtk.Menu used.  Its size seems to be limited by the height of the headerbar (even if attached to and shown on a larger widget).  There is no significant difference between the code used for this menu and the View context menu. Maybe a window manager issue?  May have to use a popover instead.  As Files master is now incompatible with Hera the fix will not appear until Odin is released.

**Comment by jeremypw** [comment]
Part of the problem is that the menu does not know what size it needs to be when it is shown since it is shown before the directory has finished loading its children (in case this takes a long time). It is is possible to set the initial size larger, but it does not resize when loading is finished and the extra items added (even if size request changed manually).

**Comment by cassidyjames** [comment]
I'm no longer able to reproduce this; I wonder if something changed in Ubuntu's GTK again?

**Comment by meisenzahl** [comment]
@ryonakano are you still able to reproduce this?

**Comment by ryonakano** [comment]
@meisenzahl Yeah, unfortunately on my side. I'm using the latest updated odin and it still occurs:

![screenshot](https://user-images.githubusercontent.com/26003928/102322632-b2bf0300-3fc2-11eb-82d6-a2b72aa88aef.png)

**Comment by cassidyjames** [comment]
I am also still getting this/getting this again on an up-to-date 6.0 install, in English. It might be some sort of race condition when the menu is initialized, because I don't think I see it every time…

**Comment by hanaral** [comment]
I still get this everywhere ryonakano reported it, the application menu context menus are now not usable due to the scrollable arrows being oversized:
![2021-01-24 10 07 19 のスクリーンショット](https://user-images.githubusercontent.com/58219504/105627023-f9a6e080-5e2b-11eb-9972-00e8b533b55b.png)
