### ISSUE TITLE
Hang on first time.

### ISSUE THREAD

**Issue by ReajulHasanRaju** [elementary/applications-menu#429]
After the first boot, when I clicked on 'Application' it hangs and the whole wing-panel gone for 2/3 seconds. Then everything goes as normal.

**Comment by cassidyjames** [comment]
Could you please fill out the following information, and in the future, please use the issue template for a bug report.

>### Logs
>
>If applicable, please share logs or error messages:
>* Fails without warning? Get and share debug logs by following: https://elementary.io/docs/code/os-dev#debug-logs
>* Unexpectedly quits or stops? Get and share crash logs by following: https://elementary.io/docs/code/os-dev#inspecting-crashes
>
>
>
>## Platform Information
>
>* The version of elementary OS you are using, or other operating system
>* The version of the software you are using such as "1.0", "Compiled from git", or "Latest release" if you're not sure but you have run updates
>* Relevant hardware information such as graphics drivers, unconventional setups, etc.
>* If you're unsure, copy or screenshot information at System Settings -> About
>
>
>
