### ISSUE TITLE
Use scrolling fade on both left and right edges of grid view

### ISSUE THREAD

**Issue by hanaral** [elementary/applications-menu#431]
## Problem
It would look a lot more slick

## Proposal
Use a gradient at both edges of grid view for that nice fade-out effect

## Prior Art
Like how the language selector in code does it:

![Screenshot from 2020-11-15 11-01-26](https://user-images.githubusercontent.com/58219504/99183205-01624e80-2732-11eb-84bb-453b40a8fa3c.png)

**Comment by danrabbit** [comment]
This would require adding underscroll nodes to Hdy.Carousel. So this feature request should be pursued there.

Closing as "Out of Scope" since this is a feature request for Hdy.Carousel and can't be fixed here
