### ISSUE TITLE
Vertical Application Menu Scroll

### ISSUE THREAD

**Issue by Ppamungkas** [elementary/applications-menu#432]
Provide an options for user to have vertical scroll instead of horizontal scroll for application Menu.

## Problem
Since scrolling mostly done by mouse, it should be more natural to have vertical scroll than horizontal scroll in application menu.

## Proposal
Provide an option to user to have vertical scroll.

**Comment by danrabbit** [comment]
You can already scroll vertically with a mouse wheel to change pages :)

**Comment by Ppamungkas** [comment]
Hi @danrabbit , sorry if it is not clear before, what I meant is the application item animation. Yes you can scroll vertical with the mouse or touchpad.. but the animation will scroll horizontally... :)
