### ISSUE TITLE
Shadows are cut off in the top and bottom row

### ISSUE THREAD

**Issue by fs3o5** [elementary/applications-menu#435]
## What Happened
When you click on an icon you see that the shadows are cut off in the top and bottom row. 

## Expected Behavior
You should be able to see all shadows.

## Steps to Reproduce
Click and hold an icon.

## Platform Information
elementary OS 6

**Comment by cassidyjames** [comment]
Thanks for filing! This looks like a duplicate of https://github.com/elementary/stylesheet/issues/906
