### ISSUE TITLE
Calculator does not show all available digits in result (shows floating point number)

### ISSUE THREAD

**Issue by aral** [elementary/applications-menu#439]
## Steps to Reproduce

1. Enter 64 * 20000 in the applications menu search field

## What should happen

Should behave exactly like the calculator app whose icon it uses. i.e.,

1. Should display as 64 × 20000
2. The result should display as 1,280,000

And, if I select the result, it should open in the calculator app as it has its icon next to it.

## What actually happens

Is not consistent in behaviour with the calculator app:

1. Displays as 64 * 20000
2. Result displays in scientific notation: 1.2e+06

And, if I select the result it does not open in the calculator app.

## Platform Information

```
OS: elementary OS 5.1.7 Hera x86_64 
Host: LabTop Mk IV 
Kernel: 5.4.0-58-generic 
Uptime: 5 days, 6 hours, 55 mins 
Packages: 2047 
Shell: zsh 5.4.2 
Resolution: 1920x1080 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 4013MiB / 15883MiB 
```

**Comment by jeremypw** [comment]
I have reduced the scope of this issue to a single thing - the precision of the result so that it can be linked to a single PR.
Please feel free to open separate issues about other matters mentioned.
