### ISSUE TITLE
The menu just disappeared

### ISSUE THREAD

**Issue by AshrithSagar** [elementary/applications-menu#447]
![Screenshot from 2021-01-13 09-45-05](https://user-images.githubusercontent.com/67307254/104405916-1b7aaa80-5584-11eb-8ddf-4cb16194f909.png)
I can't find the menu.
Restarting should fix that issue. I am going to restart now.
Thank you!

**Comment by AshrithSagar** [comment]
I have noticed that #427 also is the same issue.
Should I close this one? 
(I am new here).

**Comment by donadigo** [comment]
Yes, please comment on the #427 with more details, or if you don't have any additional information, you can react with 👍 in the original issue.
