### ISSUE TITLE
super+space does not open menu on latest builds

### ISSUE THREAD

**Issue by hanaral** [elementary/applications-menu#456]
## What Happened

Right now I am unable to open the menu through its default binding, or any other binding I set. Setting the option to 'open applications menu' option from the 'Super key behaviour' drop-down doesn't seem to be effected for some reason.

## Expected Behavior

Application menu opens and closes with default or custom bind

## Steps to Reproduce

Try super+space/your custom binding on latest everything

## Platform Information

elementary OS 6 Daily

**Comment by pongloongyeat** [comment]
Works for me. Self built 20210124

**Comment by hanaral** [comment]
Cannot reproduce on newer installs, closing since until it happens again.
