### ISSUE TITLE
Use ModeSwitch instead of ModeButton

### ISSUE THREAD

**Issue by hanaral** [elementary/applications-menu#460]
## Problem

ModeButton looks like it fits the role of switching between separate content like a tab switcher. That is obviously not the case with the Applications menu, since it just changes the way the same content is presented. (A very similar looking widget used in AppCenter to switch between entirely different pages)

## Proposal

Use a ModeSwitch to imply that it is just a change in view 'mode', and nothing else. 

## Prior Art

![applications-menu-ModeSwitch](https://user-images.githubusercontent.com/58219504/107887047-53ff0280-6efb-11eb-8184-1ae8aae0de70.png)

**Comment by pongloongyeat** [comment]
A switch typically indicates that something is on/off, not a switch between states. I'm gonna have to :-1: this one :(

**Comment by hanaral** [comment]
Yeah, this was mainly an idea I had based on what I thought would be a good use-case of it the switch. I'll leave the issue here for someone with better judgement to see 😛

**Comment by danrabbit** [comment]
This is an interesting proposal, but we also have view switchers in other apps, like Files and Music with more than 2 states, so changing this here would introduce inconsistency in the widget used for view switching. So, I'm inclined to close this as "Design Conflict"
