### ISSUE TITLE
elementary 6:Applications menu doesn't show icons

### ISSUE THREAD

**Issue by jcamposz** [elementary/applications-menu#463]
Applications menu and dock don't show some icons for elementary applications, exactly, for calendar, screenshot app and photos.

![imatge](https://user-images.githubusercontent.com/11057356/109328059-4e89ac80-7859-11eb-9256-f7b98854f5f9.png)
![imatge](https://user-images.githubusercontent.com/11057356/109328206-7aa52d80-7859-11eb-8702-a143ba417a2d.png)

My system is installed using spanish languae, but my user is configurated with catalan. If I change the language for my user session to spanish,the icons appear.

I don't know if this is caused by different languages or by using catalan language.

**Comment by davidmhewitt** [comment]
Someone had translated the icon names in the Catalan translation, which broke them.

I've fixed the translations in [Weblate ](https://l10n.elementary.io/) for the 3 apps you mentioned so should be resolved in an update.

I'll close this issue as it is a problem with the translations, not the applications menu.
