### ISSUE TITLE
App menu lags before it caches

### ISSUE THREAD

**Issue by zvirdaniel** [elementary/applications-menu#47]
I have a serious problem with the applications menu. I never thought it will last this long (I have this problem for **more than a year now**), so I am submitting a bug report. Basically, after every reboot, or after every app installation, the application menu is horribly slow after its launched (and it takes _seconds._ to launch). Then, I have to scroll through the entire menu to make it somewhat responsive again. After that, launching it becomes fast, and I can scroll through it normally. But if I install any app again, or even don't use the menu for too long, it becomes laggy again (before it caches, again).

This video will demonstrate, pardon the quality:
[![Demonstration video](https://img.youtube.com/vi/JW-wTl0UTkg/0.jpg)](https://www.youtube.com/watch?v=JW-wTl0UTkg)

How can I help to fix this issue? What can I do to get it solved? Note, that I do not have an SSD.

**Comment by donadigo** [comment]
Once we merge this and apply that in Slingshot this will go away: https://github.com/elementary/granite/pull/106.
