### ISSUE TITLE
Irrelevant results with all-caps search

### ISSUE THREAD

**Issue by candiedoperation** [elementary/applications-menu#474]
## What Happened

Search results are irrelevant in Wingpanel when search text is in uppercase.  (Example: **Text: 99999**)

## Expected Behavior

Search with uppercase should return same results as the ones with lowercase

## Steps to Reproduce

1. Open Applications Menu (⌘ + Space)
2. Type something in uppercase
3. Calculator ranks as the top match

https://user-images.githubusercontent.com/47198395/117439438-762f7c00-af50-11eb-9e94-c8694e75e6cf.mp4

### Logs

No Logs

## Platform Information

Operating System: elementary OS 6
Edition: (Public Beta)
Hardware Information:
- Quad-Core Intel® Core™ i5-8250U CPU @ 1.60GHz
- Intel® UHD Graphics 620 (Kabylake GT2)
- 7.7 GiB memory
- 467.2 GB storage (SSD)

Laptop Information: HP Pavilion x360

**Comment by candiedoperation** [comment]
Hello @danrabbit, @cassidyjames. There is a serious problem which causes 100% CPU Utilization which never comes down until I execute `killall bc`. I realized this after my laptop suddenly started to heat up a lot after installing Elementary OS 6 (Physical, No Virtual Machines)

When Typing in capitals (related to this issue), I think the calculator plugin `applications-menu` launches a `bc -l` instance which never gets auto killed.

In the video attached below, there are only four instances of `bc -l` which never get killed as I had demonstrated a search only a few times.

But, By the end of the day, I approximately use Applications Menu at least 20 to 30 times which causes Elementary to launch around 7 to 8 instances of `bc -l` which eats up 100% of all my cores and hence reduces performance and even scrolling lags.

I’ve demonstrated meaningless long strings in uppercase **but this applies to Webpage URL’s, Files, etc.** Which are somewhat long so, even if I type in long URLs or **long File Names in Uppercase 3 to 4 times** a day, It impacts the performance critically.

**The `bc -l` instances seriously never get killed automatically in this case.** I waited a day long and **finally executed `killall bc`** as all my 8 logical processors were at 100% utilization

**Comment by jeremypw** [comment]
This not actually unexpected for `bc` - the underlying program used to process the input. `man bc` includes the following information:
> Input numbers may contain the characters 0–9 and A–Z. (Note:
       They must be capitals.  Lower case letters are variable names.)  Single digit numbers always have the value of  the  digit  regardless  of  the
       value  of  ibase. (i.e. A = 10.)  For multi-digit numbers, bc changes all input digits greater or equal to ibase to the value of ibase-1.  This
       makes the number ZZZ always be the largest 3 digit number of the input base.

However, we probably do not want this behaviour in `applications-menu` - we only need cater or single simple expressions, not use the full power of `bc`.

A very simple fix is to convert the input to lower case before submitting to `bc`.  A better fix may be to change the regex as some expressions like `pi` and `e`, which `bc` recognizes could be useful to accept.
