### ISSUE TITLE
Incorrectly named instant answer

### ISSUE THREAD

**Issue by kdwk** [elementary/applications-menu#498]
## What Happened

![Screenshot from 2021-08-23 10-06-07](https://user-images.githubusercontent.com/39268094/130380345-90a81bcc-6954-46f6-a08f-7a7c25b6a2d5.png)

Calculation result is incorrectly shown as 'Text', which is confusing to users. What does it mean by 'text'?

## Expected Behavior

Give it a more descriptive label, like 'Calculate' or 'Compute'

## Steps to Reproduce

1. Type in a simple mathematical equation
2. Observe the label for the instant answer

## Platform Information

![Screenshot from 2021-08-23 10-10-38](https://user-images.githubusercontent.com/39268094/130380631-3bdec8d5-d6d7-4832-889b-cfba7ffd2e57.png)

**Comment by jeremypw** [comment]
The header "Text" seems to come from the match type used by the calculator plugin (MatchType.TEXT).  All entries not already parsed as e.g. an Application, Action or Link are passed to the calculator which then further parses then to see if they are calculations.  In principle there could be more than one plugin which receives unparsed entries and each would return results under the "Text" header each with its own icon.  In practice, only calculator plugin accepts unparsed text afaict so it is a bit puzzling.
