### ISSUE TITLE
PWAs disappeared from the apps menu

### ISSUE THREAD

**Issue by JoseExposito** [elementary/applications-menu#500]
## What Happened

After yesterday's update, progressive web apps disappeared from the list.

Installing new PWAs doesn't create an entry either.

Both new and previously installed PWAs are visible only while searching.

## Steps to Reproduce

1. Install a PWA using Chrome
2. The app is not available in the apps menu

## Platform Information

elementary OS 6
slingshot-launcher 2.8.1

**Comment by davidmhewitt** [comment]
Please can you attach the .desktop file of one of these?

**Comment by JoseExposito** [comment]
Thanks for the quick response @davidmhewitt, here is Twitter's desktop file:

```bash
$ cat .local/share/applications/chrome-panfkkhihbglmaommdcbgghogdofkjpi-Default.desktop
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Twitter
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=panfkkhihbglmaommdcbgghogdofkjpi
Icon=chrome-panfkkhihbglmaommdcbgghogdofkjpi-Default
StartupWMClass=crx_panfkkhihbglmaommdcbgghogdofkjpi
```

**Comment by davidmhewitt** [comment]
Great thanks, that's a regression of #496 and I can see what the issue is.

PR incoming!
