### ISSUE TITLE
Visual glitch when clicking away from context menu

### ISSUE THREAD

**Issue by D0J0P** [elementary/applications-menu#512]
### What Happened?

When right-clicking on an app, and then clicking away somewhere in Applications Menu to exit, there's a line that shows up to the right of the app icon previously clicked. I tried to take a screenshot, but that makes it disappear. 

### Steps to Reproduce

1. Open Applications Menu
2. Right-click any app to open the context menu
3. Click away from the context menu to make it disappear.
4. Notice a line to the right of the context menu appeared
5. You might have to do this a few times for it to work

### Expected Behavior

That no visual line would show when clicking away from the context menu. 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by hirusi** [comment]
This issue is present on 6.1 as well.

**Comment by lenemter** [comment]
Duplicate of https://github.com/elementary/gala/issues/605
