### ISSUE TITLE
Entering search terms in capitals results in unexpected calculation

### ISSUE THREAD

**Issue by jeremypw** [elementary/applications-menu#538]
### What Happened?

When entering a search term with CAPSLOCK accidentally on, a calculation result was shown:

![Screenshot from 2022-07-04 19 57 15](https://user-images.githubusercontent.com/10513844/177206468-c2f402da-9638-4727-b256-bba7c7af79a0.png)

Some experimentation showed that a single letter produced a sensible answer based on A = 10, B = 11 etc but two letters always returned 99, three letters 999 etc.

Not sure if this is an attempt to give a hexadecimal conversion but in anycase it would make more sense to only perform a calculation if the search term finished with `=`.

### Steps to Reproduce

1. Open the Application Menu
2. Type something in capital letters
3. See strange calculation result

### Expected Behavior

Calculations should only be performed an actual expressions and should give the correct answer

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by peteruithoven** [comment]
This might be a duplicate of #474?

**Comment by jeremypw** [comment]
Oops yeah, this has been reported several times before.  Closing.
