### ISSUE TITLE
Searching "next" shows calculated 0 as result

### ISSUE THREAD

**Issue by peteruithoven** [elementary/applications-menu#566]
### What Happened?

When searching for "next" (or "Firefox beta") it shows calculator output 0 as first result. 
![Screenshot from 2023-06-10 01 09 05@2x](https://github.com/elementary/applications-menu/assets/523210/a6b83e5a-ac14-4ab4-b9de-8180b35a5e31)

### Steps to Reproduce

1. Open applications menu
2. Type "next"

### Expected Behavior

No calculated result is shown

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by peteruithoven** [comment]
Looks like we replace the "x" with "*":
https://github.com/elementary/applications-menu/blob/master/src/synapse-plugins/calculator-plugin/calculator-plugin-backend.vala#L60

Afterwards "ne*t" matches the following regexp:
https://github.com/elementary/applications-menu/blob/master/src/synapse-plugins/calculator-plugin/calculator-plugin-backend.vala#L44
Example: https://regex101.com/r/CHWvjt/1

**Comment by peteruithoven** [comment]
For reference, current reg exp: `^.*(\w+[\/\+\-\*\^\%\!\&\|]{1,2}\.?\w+|\(-?\d+.*\))+.*$`. 
What if we go with something like: `^([-\d.]+[\/\+\-\*\^\%\!\&\|]{1,2}[-\d.]+)+$`
- Uses more specific `\d` instead of `\w`. Also supporting "-" and ".".
- Removed `.*` at start and end, because it's not clear for me why they are there?
- Removed the `\.?` before the `\w+`. Why only allow an optional . before the \w here?
- Removed `|\(-?\d+.*\)` because it's not in line with the description of "<alphanum><operator><alphanum>"

Example: https://regex101.com/r/aSz5MI/1

Would be really great to have some unit tests on this part, because I'm probably forgetting about many usecases.

**Comment by peteruithoven** [comment]
Looking for "Firefox beta" also returns the 0.

**Comment by jeremypw** [comment]
Looks like the "x" is interpreted as "multiply" even though the other parts are non-numeric and presumably parse to "0". Should be easy enough to check the non-operator parts are actually numbers?

**Comment by jeremypw** [comment]
Firefo^ Beta = 1 (interpreted as 0 ^ 0.

**Comment by jeremypw** [comment]
As `bc` can handle multiple expressions it is possible for `next` to be a valid expression: e.g. `ne=3;t=4;next` gives the expected result `12`.  The code in this app is too simplistic to handle this kind of thing. It just passes a string that *might* be a valid mathematical expression(s) to `bc` and returns the result if `bc` gives no error.  Unfortunately `bc` does not give an error for undefined variables - just assigns them the value `0`.  Whether it is worth us trying to check for undefined variables here is questionable.
