### ISSUE TITLE
Changing icons doesn't appply any more to Applications-Menu

### ISSUE THREAD

**Issue by SethStormR** [elementary/applications-menu#583]
### What Happened?

Hello, 
I'm using elementary OS 7.1 and have the issue regarding changing icons via AppEditor which can be downloaded with AppCenter. I'm not sure if it's a problem with AppEditor or with Applications-menu. The icons in Plank on the other hand changes when you drag them from applications-menu to Plank. So I guess the problem must be with applications-menu.

with best Regards
Seth Storm R.

### Steps to Reproduce

Install AppEditor
Open AppEditor and change icon and then save.
Nothing happens.

### Expected Behavior

Changing the icons.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
I think this is related to https://github.com/elementary/wingpanel/issues/513, so I'll close this issue as duplicate.
