### ISSUE TITLE
Set tooltip with keyboard shortcut

### ISSUE THREAD

**Issue by cassidyjames** [elementary/applications-menu#59]
For discoverability, Slingshot should set a tooltip with its keyboard shortcut (⌘ + Space).

**Comment by danrabbit** [comment]
Should we include some more info like "Launch and search apps, settings, and actions"?

**Comment by cassidyjames** [comment]
I was wondering that, but that's what lead me to thinking about #60. Instead of tucking that behind a tooltip, we could just be better about the label.

I'm also open to being even more descriptive in the tooltip, though.
