### ISSUE TITLE
Use Gala interface for launch/focus

### ISSUE THREAD

**Issue by danirabbit** [elementary/applications-menu#593]
### Problem

launching behavior between the applications menu and the dock now differs because we have better wm integration in the dock

### Proposal

We should re-use the behavior from the dock where we activate apps with 0 windows, focus with 1 window, and window spread for 2 or more windows

### Prior Art (Optional)

https://github.com/elementary/dock/blob/main/src/App.vala#L68

**Comment by tintou** [comment]
Should we? The thing is, how do I open another window?

**Comment by danirabbit** [comment]
@tintou you can use "New window" from the context menu, we can set up middle click as described here: https://github.com/elementary/dock/issues/77#issuecomment-1821781386 or use whatever mechanism that exists in the app for creating a new window :woman_shrugging:

**Comment by danirabbit** [comment]
Ah I guess this is a duplicate of #464
