### ISSUE TITLE
"Add to Dock" and "Remove from Dock" menu item with the our new dock

### ISSUE THREAD

**Issue by ryonakano** [elementary/applications-menu#596]
### Problem

We'll ditch Plank and ship our own dock instead from elementary OS 8. When elementary OS 7.x or before, we have "Add to Dock" and "Remove from Dock" menu item when we clicked an app icon, but it's not in latest Early Access

### Proposal

Add "Add to Dock" and "Remove from Dock" menu item with the our new dock as before when Plank is used.

### Prior Art (Optional)

The "Add to Dock" and "Remove from Dock" menu item in Applications Menu in previous OS versions.

![Screenshot from 2024-05-19 15-17-00](https://github.com/elementary/applications-menu/assets/26003928/4f270812-2f1d-481d-981c-933063f60d2d)

![Screenshot from 2024-05-19 15-17-16](https://github.com/elementary/applications-menu/assets/26003928/789a0258-a3cb-4067-bf41-0cbca61aa6c7)

**Comment by danirabbit** [comment]
This was fixed in #578

**Comment by ryonakano** [comment]
Ah, I didn't know that. Thank you for letting me know that!

Launching `io.elementary.dock` from Terminal I confirmed these menu items exist, so I'll close this issue as invalid.
