### ISSUE TITLE
Keyboard shortcut doesn't launch the menu

### ISSUE THREAD

**Issue by dar5hak** [elementary/applications-menu#608]
### What Happened?

On Circe RC, pressing `Alt` + `F2` doesn't open the menu. I changed the shortcut to `Super` + `Space`, but that doesn't work either.

### Steps to Reproduce

1. Boot into Circe RC.
2. Press the shortcut to launch Applications Menu.

Nothing happens.

### Expected Behavior

The menu opens.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Tried both builtin and external keyboard.

**Comment by danirabbit** [comment]
Probably fixed by https://github.com/elementary/default-settings/pull/316

**Comment by ryonakano** [comment]
@danirabbit [The LP recipe](https://code.launchpad.net/~elementary-os/+recipe/default-settings-stable) is set to "Build on request" so we need to trigger build or switch to "Build daily"

**Comment by danirabbit** [comment]
@ryonakano running now :) I think the import was just scheduled while I was AFK, but I was watching it https://code.launchpad.net/~elementary-os/+recipe/default-settings-stable

**Comment by ryonakano** [comment]
Confirmed it fixed in the latest OS 8 RC.
