### ISSUE TITLE
"Uninstall" action inactive in context menu of applications

### ISSUE THREAD

**Issue by diogopessoa** [elementary/applications-menu#618]
### What Happened?

The "Uninstall" action in the context menu is inactive for both default and third-party applications.

![Captura de tela de 2024-12-01 15 21 36](https://github.com/user-attachments/assets/d3b5275e-36bf-41dd-91ed-2a646c733bcf)

system: elementary OS 8
![Captura de tela de 2024-12-01 15-22-14](https://github.com/user-attachments/assets/8994ce4e-3387-4914-af1c-52c5127c8445)

### Steps to Reproduce

1. go to the applications menu on top panel
2. right click on icon application to open the context menu

### Expected Behavior

The "uninstall" action in the applications menu should work.

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by teamcons** [comment]
Duplicate of https://github.com/elementary/applications-menu/issues/609
