### ISSUE TITLE
Mouse scroll doesn't work anymore.

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/applications-menu#64]
From a few days back, mid-December, mouse scroll stopped working so now the only way to go through a multi-page category is by clicking the pagination dots.
Since I don't remember seeing a slinghot update recently, this is maybe a different issue so I apologize if this bug report hits the wrong repo.

**Comment by dark2y** [comment]
+1 Same here. Mouse scroll just stopped working.

**Comment by dark2y** [comment]
Hi Guys. 

I have a 1 line fix for this, can you instruct me on how i can get it over to you guys? 

Thanks

**Comment by tintou** [comment]
Okay, so do the following:

1. Click on the `fork` button on the top right of the page and fork the project under your personal account.
2. Click the `Clone or Download` green button and copy the URL
3. In your terminal type `git clone [PASTE THE URL WITHOUT THE BRACKETS]`
4. Make the changes in the created folder
5. Add all your changes with `git add FILENAME` and then type `git commit` and enter a commit message in the opened editor
6. Type `git push` to push your changes into your personal fork
7. Return to GitHub and click the `new pull request` button. Chose the appropriate branch and here you are!

Thanks for your work :)

**Comment by dark2y** [comment]
Done. Thanks.
