### ISSUE TITLE
Applications menu with big size

### ISSUE THREAD

**Issue by chauhankiran** [elementary/applications-menu#75]
Currently we have an applications menu with small size which display normally 15 apps  at a time. Can we make this window big to whole screen? For example, If I have 25-30 apps then I have scroll throught 3 pages. I know, I can use search utility to directly open that apps. But, app launcher is normally complete desktop screen nowadays such as GNOME3 has.

**Comment by danrabbit** [comment]
The reason that we stick to a smaller grid is actually based off some user testing we did to determine the largest possible grid size before it starts becoming difficult to find an icon in the grid. I'm sure others have come to similar conclusions in testing as you can see that, for example, iPad Pro's grid is 5x4 and Chrome OS's grid is only 4x4

So going to close this one as a "Design Conflict"
