### ISSUE TITLE
Search icon "joined" with Applications text in daily build 

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/applications-menu#79]
Hi.
I've just install slingshot from Daily PPA, version 2.2.0+r902+pkg71+r1~daily~ubuntu16.04.1. This is something I never do, using the Daily PPA, but mouse scroll not scrolling inside category just frustrated a hell out of me.

Anyhow, everything is peachy except that new "search icon" is attached to "Application" text, there is literally no space between them as you can see in my screenshot.

![slika zaslona 2018-03-20 16 51 22](https://user-images.githubusercontent.com/6765137/37666340-a24f629a-2c5f-11e8-9eca-0b42c9321e12.jpeg)

Cheers.

**Comment by cassidyjames** [comment]
Loki is in maintenance mode, and daily builds are no longer intended to be used on Loki. The stylesheet has some changes that Slingshot requires from Juno.
