### ISSUE TITLE
Use of Up/Down arrow keys should navigate through your search history

### ISSUE THREAD

**Issue by uncertainquark** [elementary/applications-menu#81]
When the applications menu pops-up it shows the standard view and an empty text field with the cursor focused on it. It would be a great idea if the Up/Down arrow keys can navigate through past search history for easier access.
![screenshot from 2018-03-23 12-34-34](https://user-images.githubusercontent.com/22585732/37863158-88fe8c94-2f7f-11e8-9fe1-cd50a78f3c14.png)

This will make up for the fact that unlike Unity (or similar app launchers), the pantheon applications menu doesn't remember recently searched terms.

**Comment by megatux** [comment]
But that conflicts with the cursor navigation between icon list. The focus of the "box" when using the keyboard should be more clear. Right now is a mix between the search input and the icon apps list. 
e.g.: MENU-key when navigation the icon list does trigger the input context-menu and not the selected app context-menu ("Add to dock", etc)
![menu-key-not-working](https://user-images.githubusercontent.com/850020/49313724-fe2f1300-f4c6-11e8-8328-76f94d769792.png)
![menu-key not working](https://user-images.githubusercontent.com/850020/49313726-fec7a980-f4c6-11e8-8fdd-1605a2724236.png)

**Comment by danrabbit** [comment]
I'm inclined to close this since it conflicts with keyboard nav. @cassidyjames opinions?

**Comment by cassidyjames** [comment]
Yeah. While search history might be handy, it's not essential and would need a lot more design thought.
