### ISSUE TITLE
Allow navigating to existing application instead of opening a new instance

### ISSUE THREAD

**Issue by p2kmgcl** [elementary/applications-menu#87]
Sometimes, when I use the applications menu, opening an application (for example Slack or Spotify) just reopens the existing instance instead of opening a new one.

However, for other apps like patheon-terminal, new instances are opened everytime I choose the application on the result list.

I think it would be useful to have a common pattern for distinguish opened applications and application launchers, for example providing results from the window list.

(If anyone gives me some guidance about how to extend the search results I could try to start investigating this suggestion :smile:)

**Comment by colinkiama** [comment]
To add to this, I'd love to see results able to something like the launcher on Pop!_OS.
![image](https://user-images.githubusercontent.com/16501024/123941029-acf2a300-d991-11eb-8105-6a14f3081609.png)

You can search for running app instances or open new instances of applications
