### ISSUE TITLE
Make sub-settings searchable (Startup applications, Hot corners, Dock settings, etc.)

### ISSUE THREAD

**Issue by uncertainquark** [elementary/applications-menu#94]
Important settings like "Startup applications", "Hot corners", "Dock settings" and more are not searchable from the Applications menu. 
![screenshot from 2018-05-03 14-36-24](https://user-images.githubusercontent.com/22585732/39568755-d5a1c932-4ee0-11e8-9dab-8a39b5992653.png)
![screenshot from 2018-05-03 14-36-13](https://user-images.githubusercontent.com/22585732/39568758-dc2cd670-4ee0-11e8-9cc0-bf6e49cbff3a.png)
![screenshot from 2018-05-03 14-41-27](https://user-images.githubusercontent.com/22585732/39568762-e02933d6-4ee0-11e8-8c47-7d062a574109.png)

This is happening because the Applications menu searches only for major settings modules, not within them. However, searching within the modules would enhance discoverability of such important features.

**Comment by peteruithoven** [comment]
One tricky thing is that this would require changes in Switchboard, Application launcher and all the plugs.

Currently plugs list `supported_settings` like the Desktop plug:
https://github.com/elementary/switchboard-plug-pantheon-shell/blob/master/src/desktop-plug.vala#L29-L39

This follows the Plug defined by Switchboard:
https://github.com/elementary/switchboard/blob/master/lib/Plug.vala

This info is used in Switchboard, for example to list them and search through them. 

The switchboard plugin of the Application menu uses some of the plug's info to generate a possible search result, like the display name, icon and the uri:
https://github.com/elementary/applications-menu/blob/master/lib/synapse-plugins/switchboard-plugin.vala#L96-L105

To implement searching on sub settings you'd need to specify per plug's sub setting things like: 
- human readable title, like "Hot Corners"
- uri like "desktop/hot-corners"
- icon
- code_name? (I don't really understand how that's currently used)

**Comment by donadigo** [comment]
@peteruithoven I don't think it would be that difficult. We could easily use the `search ()` function to get search results and show revelant entries, you could also as well use the same plug icon for the search result. See here: https://github.com/elementary/switchboard-plug-pantheon-shell/blob/master/src/desktop-plug.vala#L97

**Comment by peteruithoven** [comment]
Good point! 
But this search returns a location, like "hotc", which then would need to be mapped, possibly using `supported_settings` to a url? A bit awkward, but this would require a lot less changes.

**Comment by peteruithoven** [comment]
Wait, no, that still wouldn't give us the human readable title?

**Comment by donadigo** [comment]
@peteruithoven thank you for the work and actual implementation. Closing then :)
