### ISSUE TITLE
Hide apps

### ISSUE THREAD

**Issue by ssspacez** [elementary/applications-menu#97]
How about implementing a feature of hiding apps?

You **right-click** on a icon, it shows a "**Hide application**", you hide it, and if you want to show it again you just **right-click somewhere on the menu** and click "**Show hidden applications**" and it comes back.

This is similar to what some Menu Editors do, but in this case you will not need an external application to do that.

**Comment by jwinnie** [comment]
@ssspacez Why would you want to hide an app? If you don't want it, you can just uninstall it.

**Comment by ssspacez** [comment]
To make the menu look cleaner, get rid of the clutter, there is always something that you never use, for example for me I never use LibreOffice Draw and it came with the snap package, I don't care about the extra space on disk, it's faster to just hide it, maybe one day in the future if I need it I could inside it. I would hide Gdebi that I've installed too, you don't need to click on it to use it.

There are probably more uses for this, for example a company that doesn't want to allow access to some apps, parents that don't want the kids to use certain apps, I don't know... Some people like to edit the menu. 

More ideas are welcome, I'm seeing some apps with a "Uninstall" option when you right-click on it but not all of them have this feature.

**Comment by ssspacez** [comment]
It could have a lock feature that asks for the password to hide and unhide the apps.

For example a company that doesn't want the employees to change the Configurations, just hide it and put the password, this way people can't access it.

**Comment by cassidyjames** [comment]
@ssspacez that sounds redundant with the existing Parental Controls plug in Settings. Hiding the applications could be a good feature for that, but I think it's out of scope for this repo. There is a menu editor called [AppEditor](https://appcenter.elementary.io/com.github.donadigo.appeditor) you can install from AppCenter for this functionality.
